<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

</head>
<body>
 <header class="p1-display-container p1-content p1-center" style="max-width:1500px">
     <div class ="text-center">
         <div class ="py-5">
     <img class="p1-image" src="p1.png" alt="Me" width="900" height="180">
         <</div>
         <div class="py-5">
             <nav class="navbar navbar-expand-sm bg-warning navbar-.bg-warning">
             <!-- Brand -->
                 <b>
             <a class="navbar-brand" href="INDEX.PHP"> Get Started</a>
                 </b>

             <!-- Links -->
             <ul class="navbar-nav">
                 <li class="nav-item">
                     <b>
                     <a class="nav-link" href="QUIZ.php"> Banking Solution </a>
                     </b>
                 </li>
                 <li class="nav-item">
                     <b>
                     <a class="nav-link" href="investment.php"> Investment </a>
                     </b>
                 </li>
                 <li class="nav-item">
                     <b>
                     <a class="nav-link" href="contactus.php">Contact Us</a>
                     </b>
                 </li>

                 <!-- Dropdown -->
                 <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">

                     </a>
                     <div class="dropdown-menu">

                         <a class="dropdown-item" href="Aboutus.php">Theebika Iyer</a>
                         <a class="dropdown-item" href="Aboutus.php">Maya Ostiguy Hopp</a>
                         <a class="dropdown-item" href="Aboutus.php"> Nabila Tabassum</a>
                         <a class="dropdown-item" href="Aboutus.php">Ngoc Son (Samuel) Tran</a>

                     </div>
                 </li>
             </ul>
         </nav>
         <br>
         </div>



         <div class="p1-display-middle p1-padding-large p1-border p1-wide p1-text-light-grey p1-center">
             <div class="py-5">
         <h1 class="p1-hide-medium p1-hide-small p1-xxxlarge">WELCOME TO BUDGET SAVING </h1>
             </div>
             <div class="py-0">
         <h5 class="p1-hide-large" style="white-space:nowrap">Economy saving opportunity</h5>
                 </div>

     </div>
     </div>



     <div class="p1-bar p1-light-grey p1-round p1-display-bottommiddle p1-hide-small" style="bottom:-16px">
         <div class="text-center">
             <div class= "py-5">



     </div>
         </div>
     </div>
 </header>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>